### ISSUE TITLE
Erro no cancel_recogntion

### ISSUE THREAD

**Issue by gustavocuozzo** [CPqD/asr-sdk-python#3]
Pessoal, atualizei o transcritor para a versão v.1.0.0
Recebi o seguinte erro:

```
Exception ignored in: <function SpeechRecognizer.__del__ at 0x7fd867351700>
Traceback (most recent call last):
  File "/home/transcription/.local/lib/python3.8/site-packages/cpqdasr/recognizer/speech_recognizer.py", line 106, in __del__
    self.close()
  File "/home/transcription/.local/lib/python3.8/site-packages/cpqdasr/recognizer/speech_recognizer.py", line 271, in close
    self.cancel_recognition()
  File "/home/transcription/.local/lib/python3.8/site-packages/cpqdasr/recognizer/speech_recognizer.py", line 256, in cancel_recognition
    if self._send_audio_thread is not None:
AttributeError: 'SpeechRecognizer' object has no attribute '_send_audio_thread'
```

O branch/tag asr-2.13 foi removido?

**Comment by gustavocuozzo** [comment]
Adicionei uma nova tag 1.1
